### ISSUE TITLE
start/stop.sh

### ISSUE THREAD

**Issue by tiedtoastar** [MrNaif2018/bitcart-docker#4]
It may be easier for most people who don't know about bash scripting to include #!/bin/bash on the first line.

Also, btw your demo site is not up.

**Comment by MrNaif2018** [comment]
Demo site is now up.
Thank you, will add shebang to those files

**Comment by MrNaif2018** [comment]
Also I guess it should be 
#!/bin/sh
?

**Comment by MrNaif2018** [comment]
Fixed by 6cd69077a3603ec2109757a5952cc4a9a1d0c62c
